server:
  port: 8083
  context-path: /subscriber
spring:
  jackson:
    serialization:
      indent_output: true
  activemq:
    broker-url: tcp://localhost:61616
  data:
    solr:
      zk-host: localhost:9983

endpoints:
  actuator:
    enabled: true
    sensitive: false
  configprops:
    sensitive: false
  beans:
    sensitive: false
  env:
    sensitive: false