server:
  port: 8083
  context-path: /subscriber

spring:
  application:
    name: subscriber
  jackson:
    serialization:
      indent_output: true
  activemq:
    broker-url: tcp://localhost:61617
  boot:
    admin:
      url: http://localhost:8084/admin

management:
  security:
    enabled: false

